### ISSUE TITLE
Sensors states lost

### ISSUE THREAD

**Issue by mathieucarbou** [hekmon/rtetempo#3] opened 2023-02-02 19:17 UTC
Sensor states become unavailable after some time and and refreshing the extension does not help.
![image](https://user-images.githubusercontent.com/61346/216428327-004cc72c-5cd9-4fa3-bf7d-c96792c208f0.png)

**Comment by hekmon** [comment] 2023-02-02 19:56
I have got one of these too and I think I tracked down the issue and fixed it with 8a06997bb835ca0613ce88e7dcc9c44695eee424 (not yet released).

To go into tech details, the JSON parsing fails while the HTTP code is 200 (ok request therefor valid JSON is expected). There were safeties for errors in JSON parsing if the request was not 200 but not when the request itself indicates everything is fine. This is what the commit adds. Uncatched, this expection goes to the root of the thread and crash it (therefor no more API request are executed and you are stuck with unknown values).

I have not got the opportunity to validate the fix is actually what is needed yet (it is just a theory for now). The current workaround is "simply" to restart your home assistant in order to properly restart the crashed thread.

What would help is the integration DEBUG logs to track down its origin (tell me if you need help to setup and recover them).

**Comment by mathieucarbou** [comment] 2023-02-02 20:03
Awesome! I saw some errors too in the logs. But not sure: you need the logs from here right ?
![image](https://user-images.githubusercontent.com/61346/216436747-711aa62f-7acb-4ae3-853e-a048f8e5fc34.png)

If so, here are some I got:

```
2023-02-02 16:37:03.871 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for rtetempo using this method at custom_components/rtetempo/__init__.py, line 37: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
2023-02-02 16:37:04.127 ERROR (RTE Tempo API Worker) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/rtetempo/api_worker.py", line 94, in run
    end = self._update_tempo_days(
  File "/config/custom_components/rtetempo/api_worker.py", line 259, in _update_tempo_days
    payload = response.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
```

```
2023-02-02 16:37:14.193 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform rtetempo is taking over 10 seconds.
```

```
2023-02-02 19:57:27.481 ERROR (RTE Tempo API Worker) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/rtetempo/api_worker.py", line 94, in run
    end = self._update_tempo_days(
  File "/config/custom_components/rtetempo/api_worker.py", line 259, in _update_tempo_days
    payload = response.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-02-02 19:59:24.302 ERROR (RTE Tempo API Worker) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/rtetempo/api_worker.py", line 94, in run
    end = self._update_tempo_days(
  File "/config/custom_components/rtetempo/api_worker.py", line 259, in _update_tempo_days
    payload = response.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

```
023-02-02 20:00:20.954 ERROR (RTE Tempo API Worker) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.10/site-packages/simplejson/decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/rtetempo/api_worker.py", line 94, in run
    end = self._update_tempo_days(
  File "/config/custom_components/rtetempo/api_worker.py", line 259, in _update_tempo_days
    payload = response.json()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I actually have a lot lol ;-)

**Comment by hekmon** [comment] 2023-02-02 20:06
wow, "lucky" you ! I only got one :D

But yes, this is exactly the same as mine. You can grab the potential fix directly on the main branch if you want to try it before we can validate it actually fixes the issue and release a v1.2.1 :)

**Comment by hekmon** [comment] 2023-02-02 20:11
So yes, definitely I think there is an issue upstream with the RTE API answering 200 but not forwarding the expect JSON payload it should. But no matter, the integration should gracefully handle this case and not crash.

So the fix will have the integration return an error on this particular API call but handle it as an error and retry a bit later, no more crashed thread.

If you could test the [file with the fix](https://github.com/hekmon/rtetempo/blob/8a06997bb835ca0613ce88e7dcc9c44695eee424/custom_components/rtetempo/api_worker.py) and see if it fixes the issue on your side too, that would be great (the more confirmation, the better before a potential release).

**Comment by mathieucarbou** [comment] 2023-02-02 20:11
Can't you "tag" a new beta so that it becomes available in HACS ?

![image](https://user-images.githubusercontent.com/61346/216439050-410365bc-3ad0-4e83-ae21-4514dc51ee36.png)

I've used HACS to install...

**Comment by hekmon** [comment] 2023-02-02 20:17
Ho ! I prepared the files for a future HACS integration but the icon integration [has not been accepted](https://github.com/home-assistant/brands/pull/4097) by HA yet and HACS requires the extension to have it. I was not aware it was already working with HACS !

Let's tag it for you.

**Comment by mathieucarbou** [comment] 2023-02-02 20:19
So the integration is not officially available through HACS repo search, but we can manually add the repo, which I did ;-)

Note: I've manually patched the file with vscode meanwhile, and have restarted. 
I will report back tomorrow evening after 1 day ;-)

If meanwhile you can issue an official beta from master I will get it from HACS in order to not just test 1.2.0 + the patch, but instead have the latest master ;-)

**Comment by hekmon** [comment] 2023-02-02 20:20
I just tagged it for you https://github.com/hekmon/rtetempo/releases/tag/v1.2.1-beta1

**Comment by mathieucarbou** [comment] 2023-02-02 20:22
> I just tagged it for you https://github.com/hekmon/rtetempo/releases/tag/v1.2.1-beta1

Nice! Let's play with that right away. I will report tomorrow evening!

Thanks a lot for you kind and prompt help! You're awesome!

![image](https://user-images.githubusercontent.com/61346/216441351-77acb8b3-b5e6-433d-b600-1d33058971f6.png)

**Comment by hekmon** [comment] 2023-02-02 20:23
Thanks for helping me squashing bugs out 😊

**Comment by mathieucarbou** [comment] 2023-02-02 20:26
No worry ! That's normal...

I am trying to integrate that with the energy panel, to get the right kWh cost depending on the current color and time, and also try to have some utility meters to be able to follow the energy per color and per HC / HP.

I will share all that one done if you want.

And... If not because you already have something in place,  I would be glad to know also 😄

**Comment by hekmon** [comment] 2023-02-02 21:08
If you find how to do it for monitored devices, I would gladly know how !

But if this is for the global kWh consumed I already got this:
![image](https://user-images.githubusercontent.com/3418467/216449512-4a8691b0-c497-4897-9ae6-ba08d25e3e79.png)

Linked to manually set entity prices for each index (you do have to update it by hand when EDF release new prices like 2 days ago...)

**Comment by mathieucarbou** [comment] 2023-02-02 21:09
OK you are using the linky integration.

I have some Shelly EM to monitor. I have to set some entries (input) in HA for all the flavors lol. I will share once done.

**Comment by mathieucarbou** [comment] 2023-02-02 21:12
wait.. Are you ? I mean... You have defined several sensors to measure grid import but how they were defined ? They come from linky integration or you did add some utility meters linked to prices ?

**Comment by hekmon** [comment] 2023-02-02 21:14
Ok so this is to monitor a single device or single line, not the overall consumption, got it :)

You could use as a starting point:
- `sensor.rte_tempo_couleur_actuelle`
- `binary_sensor.rte_tempo_heures_creuses`
- bundled into a custom [template sensor](https://www.home-assistant.io/integrations/template/) to get the right price at the right time

**Comment by hekmon** [comment] 2023-02-02 21:15
> wait.. Are you ? I mean... You have defined several sensors to measure grid import but how they were defined ? They come from linky integration or you did add some utility meters linked to prices ?

They are standard indexes from the Linky TIC protocol. I just retreived them directly thru my other [home assistant integration](https://github.com/hekmon/linkytic) ;)

**Comment by mathieucarbou** [comment] 2023-02-02 21:19
> > wait.. Are you ? I mean... You have defined several sensors to measure grid import but how they were defined ? They come from linky integration or you did add some utility meters linked to prices ?
> 
> They are standard indexes from the Linky TIC protocol. I just retreived them directly thru my other [home assistant integration](https://github.com/hekmon/linkytic) ;)

Ok! Easy then! The TIC DIN is nice but I would need a WiFi solution in my case...

**Comment by mathieucarbou** [comment] 2023-02-02 21:20
yes that's what I did so far:

```
      - name: cost_edf_tempo_now
        unique_id: "01e37eed-3045-4eee-a786-1249567fe600"
        state_class: measurement
        device_class: monetary
        unit_of_measurement: "EUR/kWh"
        state: |-
          {% set t = states.sensor.time.state %}
          {% set c = states.sensor.rte_tempo_couleur_actuelle.state | lower %}
          {% set h = 'hp' if t >= "06:00" and t < "22:00" else 'hc' %}
          {{ states("input_number.cost_edf_tempo_" + c + "_" + h) | float }}
```

And I have a bunch of inputs:

![image](https://user-images.githubusercontent.com/61346/216452108-870f1103-0b45-47df-8aa8-04434b014cf7.png)

**Comment by hekmon** [comment] 2023-02-02 21:29
I define my prices like [this](https://gist.github.com/hekmon/33cba41728bfe2e4e522851da052f91f).

For your template sensor, you could simplify it by using the `binary_sensor.rte_tempo_heures_creuses` to avoid testing hours yourself but your solution works just fine.

> Ok! Easy then! The TIC DIN is nice but I would need a WiFi solution in my case...

If the issue is that your Home Assistant is not near your linky, you could "hack" it this:
- use a TIC DIN and plug it to a small low power device like a raspberry pi which has WiFi connectivity
- start a serial [rfc2217 server](https://github.com/pyserial/pyserial/blob/master/examples/rfc2217_server.py) to forward the serial connection thru TCP over WiFi
- use my [linkytic integration](https://github.com/hekmon/linkytic) and enter the [rfc2217 TCP/IP address](https://pyserial.readthedocs.io/en/latest/url_handlers.html) of the device during the setup where your Home Assistant is located

One user of the integration already does this (he is the one that has [integrated](https://github.com/hekmon/linkytic/pull/4) rfc2217 into the integration for his own usage ;)

**Comment by hekmon** [comment] 2023-02-02 21:51
I think we can use informations from #4 as confirmation for the fix. I will release the new version :)

**Comment by hekmon** [comment] 2023-02-02 21:56
fixed in https://github.com/hekmon/rtetempo/releases/tag/v1.2.1

**Closed by hekmon** 2023-02-02 21:56 UTC

**Comment by mathieucarbou** [comment] 2023-02-02 21:57
Regarding the price integration, I have the different inputs like you have, and I have the ability to derive the current price based on these inputs and this integration (hc/hp + color).

But the difficulty I have is that I only have one energy sensor from my Shelly EM. I would need a way to derive different utility meters from one energy sensor, each one of them linked to a color / hp/hc like you hvae I guess directly from the linky integration ?

**Comment by mathieucarbou** [comment] 2023-02-02 22:01
I'll try to get some inspirations from https://www.canaletto.fr/post/home-assistant-and-energie

**Comment by hekmon** [comment] 2023-02-02 22:02
You would need to extract the delta/increase of your single index (something Home Assistant does internaly for the energy dashboard with an hidden sensor) and add it to the right index given your detection off color + hc.

While I am sure this is technically possible, I do not know how. Your are in for some headache I think.

I would say: do not over complexify it more than it needs to be. If you want your tempo indexes... go grab your tempo indexes from your linky, this is the best and simplest way to do it :')

**Comment by hekmon** [comment] 2023-02-02 22:03
> I'll try to get some inspirations from https://www.canaletto.fr/post/home-assistant-and-energie

Good luck ! (and have fun x)

**Comment by hekmon** [comment] 2023-02-02 22:05
And give [rfc2217](https://github.com/hekmon/rtetempo/issues/3#issuecomment-1414398733) a chance if you can not crack it ;)

**Comment by mathieucarbou** [comment] 2023-02-02 22:05
> I would say: do not over complexify it more than it needs to be. If you want your tempo indexes... go grab your tempo indexes from your linky, this is the best and simplest way to do it :')

But where would be the fun then 😅

**Comment by mathieucarbou** [comment] 2023-02-02 22:11
> And give [rfc2217](https://github.com/hekmon/rtetempo/issues/3#issuecomment-1414398733) a chance if you can not crack it ;)

I have some ESP32 at home, so if I am to do something I would probably flash an ESP32 and use this: https://forum.hacf.fr/t/esphome-linky-mode-standard/9432 this is something I had in mind but for now I was always able to get around. But this tempo thing is complex lol ;-)

**Comment by hekmon** [comment] 2023-02-02 22:13
> > And give [rfc2217](https://github.com/hekmon/rtetempo/issues/3#issuecomment-1414398733) a chance if you can not crack it ;)
> 
> I have some ESP32 at home, so if I am to do something I would probably flash an ESP32 and use this: ~https://forum.hacf.fr/t/esphome-linky-mode-standard/9432~ https://esphome.io/components/sensor/teleinfo.html this is something I had in mind but for now I was always able to get around. But this tempo thing is complex lol ;-)

In that case, use your esp32 to forward the TIC value in MQTT, this is the simplest setup with an ESP and a TIC module (a coworker is doing just that actually).

**Comment by mathieucarbou** [comment] 2023-02-02 22:15
thanks a lot for your help!

**Comment by Binifada1956** [comment] 2023-02-22 12:46
> vielen Dank für deine Hilfe!

Salut Mathieu !
as-tu progressé avec Shelly em et Tempo ?

**Comment by mathieucarbou** [comment] 2023-02-22 12:47
> > vielen Dank für deine Hilfe!
> 
> Salut Mathieu ! as-tu progressé avec Shelly em et Tempo ?

Oui j'ai une solution qui tourne super bien avec RTE Tempo et Home Assistant! Tout fonctionne bien. J'utilise un automatisme qui va sélectionner le bon compteur d'énergie en fonction des changement HC/HC et couleur.

**Comment by Binifada1956** [comment] 2023-02-22 13:58
> > > vielen Dank für deine Hilfe!
> > 
> > 
> > Salut Mathieu ! as-tu progressé avec Shelly em et Tempo ?
> 
> Oui j'ai une solution qui tourne super bien avec RTE Tempo et Home Assistant! Tout fonctionne bien. J'utilise un automatisme qui va sélectionner le bon compteur d'énergie en fonction des changement HC/HC et couleur.
> 


... donc tu as résolu le problème des différents compteurs, rouge, blanc, bleu, ainsi que HC/HP en relation avec Shelly ?

J'utilise actuellement Verte Electrique HC/HP et j'aimerais passer au Tempo. Je me demande si je vais continuer avec le Shelly ou si je vais passer au ZLinky_Tic.

Ta solution m'intéresse, vas-tu la publier ?

**Comment by Binifada1956** [comment] 2023-02-25 16:05
@mathieucarbou  Your information about the Tempo tariffs in connection with the Shelly EM has helped me a lot. Thank you very much for that 👍
Do you have any idea how to change the colours for the tariffs.

Greetings Rolf

**Comment by mathieucarbou** [comment] 2023-02-25 16:07
> @mathieucarbou  Your information about the Tempo tariffs in connection with the Shelly EM has helped me a lot. Thank you very much for that 👍
> Do you have any idea how to change the colours for the tariffs.
> 
> Greetings Rolf

I've raised an issue in HA for that, but I saw you've seen it lol 😆
